#!/bin/bash
# Run from the repo root directory.

docker run \
  --rm \
  --network host \
  --tty --interactive \
  --volume "$PWD/examples/docker/prometheus.yaml:/etc/prometheus/prometheus.yml" \
  prom/prometheus
